{
 "title": "DNS sanity",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Domains DNS sanity",
   "type": "stat",
   "gridPos": { "h": 17, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dns_sanity_domain_mx_record{domain!=\"\"}",
     "legendFormat": "MX {{domain}}"
    },
    {
     "expr": "dns_sanity_domain_spf_record{domain!=\"\"}",
     "legendFormat": "SPF {{domain}}"
    },
    {
     "expr": "dns_sanity_domain_dkim_record{domain!=\"\"}",
     "legendFormat": "DKIM {{domain}}"
    },
    {
     "expr": "dns_sanity_domain_dmarc_record{domain!=\"\"}",
     "legendFormat": "DMARC {{domain}}"
    }
   ]
  },
  {
   "title": "Server IP address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dns_sanity_mailserver_ip", "legendFormat": "IP" }
   ]
  },
  {
   "title": "Server DNS sanity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dns_sanity_server_a_record{hostname!=\"\"}",
     "legendFormat": "DNS A {{hostname}}"
    },
    {
     "expr": "dns_sanity_server_ptr_record{ip!=\"\"}",
     "legendFormat": "Reverse DNS PTR {{ip}}"
    }
   ]
  },
  {
   "title": "Domain SPF record (copy+paste)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dns_sanity_example_spf_record", "legendFormat": "{{spf}}" }
   ]
  },
  {
   "title": "DMARC records (copy+paste to DNS)",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 3 },
   "targets": [
    {
     "expr": "dns_sanity_example_dmarc_record",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DMARC records (copy+paste to DNS)",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 10 },
   "targets": [
    { "expr": "dns_sanity_example_dkim_record", "legendFormat": "__auto" }
   ]
  }
 ]
}