{
 "title": "dovecot",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All inboxes size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_inbox_size{domain=\"__total__\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Inbox Size",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "email_inbox_size{user!=\"__total__\", domain!=\"__total__\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Successful Authentications (1s rate, 30s avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "rate(dovecot_auth_success_total[30s])*30",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Failed logins",
   "type": "table",
   "gridPos": { "h": 16, "w": 5, "x": 19, "y": 0 },
   "targets": [
    { "expr": "dovecot_auth_failures_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Domains Inboxes Size",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "email_inbox_size{user=\"__total__\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Failed Authentications (1s rate, 30s avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "rate(dovecot_auth_failures_total[30s])*30",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Mails delivered",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "targets": [
    { "expr": "dovecot_mail_delivery_total", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "Successful logins",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 9 },
   "targets": [
    { "expr": "dovecot_auth_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IMAP commands",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "dovecot_imap_command_total{cmd_name!=\"\",tagged_reply_state!=\"\"}",
     "legendFormat": "{{user}}: {{cmd_name}}"
    }
   ]
  },
  {
   "title": "IMAP command duration",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "dovecot_imap_command_duration_seconds_total{cmd_name!=\"\", tagged_reply_state!=\"\"}",
     "legendFormat": "{{user}}: {{cmd_name}}"
    }
   ]
  }
 ]
}