{
 "title": "Fail2ban",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    { "expr": "f2b_jail_failed_current", "legendFormat": "{{jail}}" }
   ]
  },
  {
   "title": "Jail configuration",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "f2b_config_jail_ban_time", "legendFormat": "ban time" },
    { "expr": "f2b_config_jail_find_time", "legendFormat": "__auto" },
    { "expr": "f2b_config_jail_max_retries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Banned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    { "expr": "f2b_jail_banned_current", "legendFormat": "{{jail}}" }
   ]
  }
 ]
}