{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mailserver_version", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 0 },
   "options": {
    "content": "<br/>\n<h3 style=\"text-align:center\"> <a href=\"/monitoring/d/dvct/\">Dovecot IMAP server</a></h3>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "postmaster_unread_emails", "legendFormat": "Postmaster unread mails" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "email_inbox_size{domain=\"__total__\"}",
     "legendFormat": "All inboxes"
    }
   ]
  },
  {
   "title": "TLS Cert Expires In",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssl_certificate_expiration_seconds_validity_left",
     "legendFormat": "\"\""
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_total - (system_memory_free + system_memory_buffers_cached)",
     "legendFormat": "Used"
    },
    { "expr": "system_memory_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_storage_used", "legendFormat": "used" },
    { "expr": "system_storage_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "1m load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_loadavg_1m", "legendFormat": "1m load" },
    { "expr": "system_num_cores", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Successful logins",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 2 },
   "targets": [
    { "expr": "dovecot_auth_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Successful Authentications (1s rate, 1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 2 },
   "targets": [
    {
     "expr": "rate(dovecot_auth_success_count[1m])*60",
     "legendFormat": "Avg. success per second"
    }
   ]
  },
  {
   "title": "User Inbox Size",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "email_inbox_size{user!=\"__total__\", domain!=\"__total__\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "TLS Cert Expires On",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssl_certificate_expiration_date_seconds * 1000",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "1m load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "system_loadavg_1m", "legendFormat": "1m load" },
    { "expr": "system_loadavg_5m", "legendFormat": "5m load" },
    { "expr": "system_loadavg_15m", "legendFormat": "15m load" },
    { "expr": "system_num_cores", "legendFormat": "# cores" },
    { "expr": "system_running_procs", "legendFormat": "Active processes" }
   ]
  },
  {
   "title": "Failed Authentications (1s rate, 1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 7 },
   "targets": [
    {
     "expr": "rate(dovecot_auth_failures_count[1m])*60",
     "legendFormat": "Avg. fails per second"
    }
   ]
  },
  {
   "title": "Mails delivered",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "targets": [
    { "expr": "dovecot_mail_delivery_total", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "Failed logins",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 9 },
   "targets": [
    { "expr": "dovecot_auth_failures_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memoy & Swap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "system_memory_used", "legendFormat": "Mem used" },
    { "expr": "system_memory_buffers_cached", "legendFormat": "Buffers + Cache" },
    { "expr": "system_memory_shared", "legendFormat": "Shared" },
    { "expr": "system_memory_free", "legendFormat": "Free" },
    { "expr": "system_swap_used", "legendFormat": "SWAP used" },
    { "expr": "system_swap_free", "legendFormat": "SWAP free" }
   ]
  },
  {
   "title": "Sieve",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "expr": "rate(dovecot_sieve_action_count[1m])*60",
     "legendFormat": "Sieve actions"
    },
    {
     "expr": "rate(dovecot_sieve_error_count[1m])*60",
     "legendFormat": "Sieve errors"
    },
    {
     "expr": "rate(dovecot_sieve_action_duration_seconds_sum[1m])*60",
     "legendFormat": "Sieve action duration"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 15 },
   "options": {
    "content": "<br/>\n<h3 style=\"text-align:center\"> <a href=\"/monitoring/d/f2bn/\">Fail2Ban</a></h3>"
   }
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "system_storage_used", "legendFormat": "used" },
    { "expr": "system_storage_available", "legendFormat": "available" }
   ]
  },
  {
   "title": "Fail & Bans count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 17 },
   "targets": [
    { "expr": "f2b_jail_banned_current", "legendFormat": "{{jail}} bans" },
    { "expr": "f2b_jail_failed_current", "legendFormat": "{{jail}} fails" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "options": {
    "content": "<br/>\n<h3 style=\"text-align:center\"> <a href=\"/monitoring/d/psfx/\">Postfix SMTP server</a></h3>"
   }
  },
  {
   "title": "SMTP Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_connects_total[1m])",
     "legendFormat": "Connects"
    },
    {
     "expr": "rate(postfix_smtpd_connections_lost_total[1m])",
     "legendFormat": "Connections lost"
    },
    {
     "expr": "rate(postfix_smtp_connection_timed_out_total[1m])",
     "legendFormat": "Timeouts"
    }
   ]
  },
  {
   "title": "Message processing rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_cleanup_messages_processed_total[5m])",
     "legendFormat": "Processed"
    },
    {
     "expr": "rate(postfix_qmgr_messages_inserted_receipients_count[1m])",
     "legendFormat": "Inserted"
    },
    {
     "expr": "rate(postfix_qmgr_messages_removed_total[1m])",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "Average delivery duration by stage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(postfix_lmtp_delivery_delay_seconds_sum[1m])) by (stage)) / (sum(rate(postfix_lmtp_delivery_delay_seconds_count[1m])) by (stage))",
     "legendFormat": "{{ stage }}"
    }
   ]
  },
  {
   "title": "Forward-confirmed reverse DNS erros",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_forward_confirmed_reverse_dns_errors_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "SASL authentication failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_sasl_authentication_failures_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Rejection ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(postfix_smtpd_messages_rejected_total[1m])",
     "legendFormat": "{{ instance }} {{code}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 37 },
   "options": {
    "content": "<br/>\n<h3 style=\"text-align:center\"> <a href=\"/monitoring/d/dnsy/\">DNS Health</a></h3>"
   }
  },
  {
   "title": "Server DNS sanity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dns_sanity_server_a_record{hostname!=\"\"}",
     "legendFormat": "DNS A {{hostname}}"
    },
    {
     "expr": "dns_sanity_server_ptr_record{ip!=\"\"}",
     "legendFormat": "Reverse DNS PTR {{ip}}"
    }
   ]
  },
  {
   "title": "Domains DNS sanity",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dns_sanity_domain_mx_record{domain!=\"\"}",
     "legendFormat": "MX {{domain}}"
    },
    {
     "expr": "dns_sanity_domain_spf_record{domain!=\"\"}",
     "legendFormat": "SPF {{domain}}"
    },
    {
     "expr": "dns_sanity_domain_dkim_record{domain!=\"\"}",
     "legendFormat": "DKIM {{domain}}"
    },
    {
     "expr": "dns_sanity_domain_dmarc_record{domain!=\"\"}",
     "legendFormat": "DMARC {{domain}}"
    }
   ]
  }
 ]
}